name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAGSEGURO_EMAIL: ${{ secrets.PAGSEGURO_EMAIL }}
      PAGSEGURO_TOKEN: ${{ secrets.PAGSEGURO_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: yarn install
    - run: yarn lint
    - run: yarn type-check
    - run: yarn test:ci --passWithNoTests
    - run: yarn build:release
      env:
        CI: true
