name: Node.js Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAGSEGURO_EMAIL: ${{ secrets.PAGSEGURO_EMAIL }}
      PAGSEGURO_TOKEN: ${{ secrets.PAGSEGURO_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: yarn install
    - run: yarn lint
    - run: yarn type-check
    - run: yarn test:ci --passWithNoTests
    - run: yarn build:release
      env:
        CI: true

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: yarn build:release
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}